version: '3.4'

services:
  solarpanelprosumer.api:
    image: ${DOCKER_REGISTRY-}solarpanelprosumerapi
    build:
      context: .
      dockerfile: SolarPanelProsumer.Api/Dockerfile
    depends_on: 
      - seq_in_solar
      - rabbit_in_solar

  solarpanelprosumer.app:
    build:
      context: .
      dockerfile: SolarPanelProsumer.App/Dockerfile
    ports:
      - "8081:80"
    depends_on: 
      - seq_in_solar

  seq_in_solar:    
    image: datalust/seq    
    ports:
      - '8005:80'      
    environment:
      - ACCEPT_EULA=Y 

  rabbit_in_solar:
    image: rabbitmq:3-management
    ports:
      - 8088:15672